### ISSUE TITLE
Dashboard, date and time has missing characters

### ISSUE THREAD

**Issue by OE9SAU** [f5vmr/svxlinkbuilder#5]
Hi Chris i used our SVXLink installer. Very good. 
Dashboard is running but s you can see on the pic the date and time has missing characters. Any hint to solve?
73 Martin, OE9SAU
![2024-06-01 23_07_20-OE9XVI fm-funknetz de Dashboard – Mozilla Firefox](https://github.com/f5vmr/svxlinkbuilder/assets/114362733/28fb3415-9466-4e81-951a-11e5d1a79beb)

**Comment by f5vmr** [comment]
The Dashboard takes a lot of information from the svxlink.conf. I wonder how you have the time configured? Have you changed from the standard time.

￼

This is my current dashboard 

http://svxportal-uk.ddns.net:19080/￼

The information is collected by the file index.php/include/lh.php to read your current time frame information. If you have changed some of that in the .conf this could cause a problem.

Now there is an issue with svxlink when compiled. Check in /etc/default/svxlink that the log function has been changed. The stock svxlink does not place .log at the end of svxlink on the /var/log . The last heard function takes the log information from svxlink.log, so if you have the log file simply as svxlink with no .log then you will have some anomalies there. 

I hope that helps you.

73 Chris

**Comment by OE9SAU** [comment]
Hi Chris, thanks for coming back. 
I changed the inside .conf, DEFAULT_LANG=de_DE

My logfile, svxlink.log having entries like this.

**_So 02 Jun 2024 10:57:01 CEST: ReflectorLogic: Node joined: DB0RM
So 02 Jun 2024 10:57:39 CEST: ReflectorLogic: Node joined: DJ7FG-HS3
So 02 Jun 2024 10:57:41 CEST: ReflectorLogic: Node joined: DD9MJ-BS
So 02 Jun 2024 10:57:43 CEST: ReflectorLogic: Node joined: DL2HBJ-HS
So 02 Jun 2024 10:57:44 CEST: ReflectorLogic: Node left: DB0ZT_**

How does yours look like?
 I changed the format to only time now, hope that could helps out.

_**11:12:18: ReflectorLogic: Connecting to service**_

73, Martin

**Comment by OE9SAU** [comment]
Hi Chris

currently there is a mixup with my date and time settings idont know.

I changed the following lines inside lh.php and lh_small.php

 if (isset($svxconfig['GLOBAL']['TIMESTAMP_FORMAT'])) {
        $local_time = substr($listElem[0],null,-11); }
        else {
        $local_time = substr($listElem[0],null,-11); }

And inside .conf the TIMESTAMP_FORMAT="%H:%M:%S"

That works out for me an showing the right time. 
Al lthe best and 73

**Comment by f5vmr** [comment]
Excellent result. Well done
