### ISSUE TITLE
Don't use sudo unless you need to

### ISSUE THREAD

**Issue by brian32768** [f5vmr/svxlinkbuilder#6]
Bad practice to use elevated permissions when you don't need them.

First example: You don't need to be root to do "git clone".
Second example in install.sh don't need root to build.

**Comment by f5vmr** [comment]
In some respects I disagree, as often I have gone through the long manual process of command line instruction and the compilation has failed owing to lack of permissions to create a folder or such, when I have forgotten to use 'sudo' ahead of the instruction. Thus sudo has been the catch-all. I disagree with the installation of this product as user root, but user 'pi' still needs permissions to create some structures during the build.
