### ISSUE TITLE
Don't install into /usr

### ISSUE THREAD

**Issue by brian32768** [f5vmr/svxlinkbuilder#7]
When installing 3rd party software, debugging and maintenance is much easier if it's installed into /usr/local

**Comment by f5vmr** [comment]
As I explained, this has been the process recommended by the Author of SVXLINK, Tobias SM0SVX. AS such a build is normal a Single Primary Use installation, there is no reason to change the install location for the sake of it being a third party application.

**Comment by brian32768** [comment]
On 2024-06-02 12:36, Chris G4NAB_F5VMR wrote:
> As I explained, this has been the process recommended by the Author of
> SVXLINK, Tobias SM0SVX. AS such a build is normal a Single Primary Use
> installation, there is no reason to change the install location for
> the sake of it being a third party application.

I've already tested it in /usr/local and it worked fine.
It's a best practice thing at making systems more reliable, but aimed at 
real computers not embedded systems.
So it's arguable how to apply it in embedded world.
I want this because I aim to move into a situation where running systems 
are easier to maintain.
