### ISSUE TITLE
Never ever do "chmod 777"

### ISSUE THREAD

**Issue by brian32768** [f5vmr/svxlinkbuilder#8]
In install.sh remove the line that chmods /etc/svxlink 

You should never ever have any folder in /etc/ with no control on write access.

**Comment by f5vmr** [comment]
See my comments on the other post.

**Comment by brian32768** [comment]
On 2024-06-02 15:03, Chris G4NAB_F5VMR wrote:
> Closed #8 as completed.

When you CLOSE AS COMPLETED
it's like saying "this is DONE" when in fact it's a TERRIBLE security 
practice.

How about re-opening it and commenting "Brian, show how you'd fix this 
issue once you know more about it"?
