### ISSUE TITLE
Do you want pull requests?

### ISSUE THREAD

**Issue by brian32768** [f5vmr/svxlinkbuilder#9]
I can submit pull requests but there are so many issues I think it would waste my time to do it one at a time,
Tell me if you want to fix problems or if you want pull requests and if you want one or 50. Okay maybe only 20. :-)

**Comment by f5vmr** [comment]
Hi Brian,
Thanks for your input.
Before I commit to taking up your offer, I would want to know your experience level.
If you want to make a fork then please do. I’m leaving the issues open as I think that you have a lot to contribute.

I’m not a perfect programmer I know. But as I have only been building svxlink repeaters for 15 years, I have found certain things work, and as the old adage goes, if it ain’t broke, don’t fix it. Far from a waste of my time, I have actually enjoyed the process of helping others get on the air with their own nodes. I probably spend more time on the software than I do on the radio to be frank.

As far as the use of sudo goes, there have been occasions when some of the operations have failed owing to permissions issues in the svxlink filing system, so sudo has always been the standard, likewise the construction and compilations has been set by the author of svxlink, Tobias SM0SVX, and I follow his recommendations as to /usr/share/svxlink for the installation, which will remain. 

SVXlink is The sole function in what essentially is a single use machine. That way any compilation can be standard, especially when it comes to advising a group in a particular fashion.

I accept that 777 is risky, but as far as the security aspect goes, in general terms these units will be stand-alone in a network that has very limited access, and each sysop has the facility to modify the security after the system is working, maybe 755 may be better. The Dashboard is particularly tricky as PHP needs permission to access the .conf files to save and edit them, outside of the web server. 

When I first built an SVXLink repeater those many years ago, I did it by hand, instruction by instruction. So I put together this script to largely automate the process for those who found programming a challenge. I added the dashboard after the fact.
In making the script, it was a challenge to me, to ensure that the software picked up whereabouts in the filing system it was, to pop in and out of the functions, so in areas I forced /home/pi while I was building it. I had removed some of these, but I was eager to get the software out there, once I got several builds made without errors, in itself an achievement. Getting sed to work correctly the way I wanted it was a particular issue, and I’m sure doesn’t work on files that are not textual. For example I need changes made to .tcl files, but the changes never appear to happen, despite the syntax being correct.

In theFaceBook "svxlink amateur radio users page", we have various tips and tricks, so please sign up there too.

Thanks

Chris G4NAB

**Comment by f5vmr** [comment]
Second thoughts, unless you are a Radio Ham, please leave this project alone as it works as it is, and I shall be refining it myself in due course. I have viewed your own content, and as far as I can tell, you appear not to have RF experience. You do suggest that you would be wasting your time, and I wouldn't want you to do that. Thanks for your input so far.

**Comment by brian32768** [comment]
On 2024-06-02 15:02, Chris G4NAB_F5VMR wrote:
> Second thoughts, unless you are a Radio Ham, please leave this project
> alone as it works as it is, and I shall be refining it myself in due
> course. I have viewed your own content, and as far as I can tell, you
> appear not to have RF experience. You do suggest that you would be
> wasting your time, and I wouldn't want you to do that. Thanks for your
> input so far.

I just read this again and it's so strange but you really don't want 
help because I am not a "Radio Ham" based on "my content"??? LOL. Ok. No 
problem. Won't write to you again!

Mick -- I think we can still continue on with what Chris does, it won't 
matter to you in the long run and the goal is to get you on the air not 
get in cat fights.

Cheers

Brian W6GKD

**Comment by brian32768** [comment]
The overall approach of installing all the source code and all the build 
tools on every Pi 4 is just fundamentally not necessary.
But it's how you're doing it... so... um... okay.

Now I really have to work.... :-)

Dang.
